// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNQuSKpJ4oDtO7Ja_UrLzWEKZphyRPF8',
    appId: '1:342610370435:web:c5b698081f33fad398e0b6',
    messagingSenderId: '342610370435',
    projectId: 'newsapp-132bd',
    authDomain: 'newsapp-132bd.firebaseapp.com',
    storageBucket: 'newsapp-132bd.appspot.com',
    measurementId: 'G-QZ0Q3D3N0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3fnE_7if6PtHUBfCUsZ038bDZNvcLew',
    appId: '1:342610370435:android:aeba53ecf02ec5e998e0b6',
    messagingSenderId: '342610370435',
    projectId: 'newsapp-132bd',
    storageBucket: 'newsapp-132bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyERA2HZgb_QF6NEaV2fCxU2IY_EdX1g',
    appId: '1:342610370435:ios:652b75a388feba9398e0b6',
    messagingSenderId: '342610370435',
    projectId: 'newsapp-132bd',
    storageBucket: 'newsapp-132bd.appspot.com',
    iosBundleId: 'com.example.newsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCyERA2HZgb_QF6NEaV2fCxU2IY_EdX1g',
    appId: '1:342610370435:ios:652b75a388feba9398e0b6',
    messagingSenderId: '342610370435',
    projectId: 'newsapp-132bd',
    storageBucket: 'newsapp-132bd.appspot.com',
    iosBundleId: 'com.example.newsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARNQuSKpJ4oDtO7Ja_UrLzWEKZphyRPF8',
    appId: '1:342610370435:web:f6ac5dc8887f6f3498e0b6',
    messagingSenderId: '342610370435',
    projectId: 'newsapp-132bd',
    authDomain: 'newsapp-132bd.firebaseapp.com',
    storageBucket: 'newsapp-132bd.appspot.com',
    measurementId: 'G-KJBBB41NWS',
  );
}
